"use client";

import React from 'react';
import { ResumeData } from './ResumePreview';

const renderBullets = (text: string) => {
  if (!text) return null;
  // Splits text generated by AI into distinct bullets
  const lines = text.split(/•|\n/).map(line => line.trim()).filter(line => line.length > 0);
  
  return (
    <ul className="list-disc list-outside ml-5 space-y-[2px] mt-1.5">
      {lines.map((bullet, j) => {
        const cleanBullet = bullet.replace(/^-/, '').trim();
        return (
          <li key={j} className="text-[13px] leading-snug pl-1">
            {cleanBullet}
          </li>
        );
      })}
    </ul>
  );
};

export default function ClassicResumePreview({ data }: { data: ResumeData }) {
  if (!data) return null;

  return (
    // Standard A4 Layout: 210x297mm approx 8.5x11 inches -> 794px min-h 1123px.
    // Strictly Black/White, Times New Roman (font-serif), base size 13px.
    <div className="bg-white text-black font-serif w-full max-w-[794px] min-h-[1123px] mx-auto shadow-xl border border-gray-200 p-[40px] pt-[50px] sm:p-[60px] sm:pt-[70px] transition-all">
      
      {/* 1. Header Array */}
      <header className="flex flex-col items-center justify-center text-center mb-6">
        <h1 className="text-[28px] sm:text-[32px] font-bold uppercase tracking-wide leading-none mb-2">
          {data.name || "CANDIDATE NAME"}
        </h1>
        <div className="flex flex-wrap justify-center items-center gap-1.5 text-[13px] leading-snug">
           {data.location && <span>{data.location}</span>}
           {data.location && (data.email) && <span>|</span>}
           {data.email && <span>{data.email}</span>}
        </div>
      </header>

      <div className="space-y-5">
        
        {/* 2. Profile / Objective (Max 256 chars mapped) */}
        {data.objective && (
          <section>
            <h2 className="text-[14px] sm:text-[15px] font-bold uppercase mb-[2px]">Profile</h2>
            <hr className="border-t border-black mb-1.5" />
            <p className="text-[13px] leading-snug text-justify">
               {data.objective}
            </p>
          </section>
        )}

        {/* 3. Education - Exact Date left, Degree/Institution center/right layout */}
        {data.education && (
           <section>
             <h2 className="text-[14px] sm:text-[15px] font-bold uppercase mb-[2px]">Education</h2>
             <hr className="border-t border-black mb-1.5" />
             <div className="flex justify-between items-start text-[13px] leading-snug">
               <div className="w-[120px] shrink-0 font-medium">To Date</div>
               <div className="flex-1 font-bold">{data.education}</div>
             </div>
           </section>
        )}

        {/* 4. Experience - Jobs */}
        {data.jobs && data.jobs.length > 0 && (
          <section>
             <h2 className="text-[14px] sm:text-[15px] font-bold uppercase mb-[2px]">Experience</h2>
             <hr className="border-t border-black mb-2" />
             <div className="space-y-4">
                {data.jobs.map((job, idx) => (
                   <div key={idx} className="flex justify-between items-start text-[13px]">
                     {/* Date Column */}
                     <div className="w-[120px] shrink-0 font-medium leading-snug mt-0.5 whitespace-nowrap">
                        {job.dates || "Date"}
                     </div>
                     {/* Role / Desc Column */}
                     <div className="flex-1">
                        <div className="font-bold leading-snug">
                          <span className="uppercase">{job.role}</span>
                          {job.org && <span>, {job.org}</span>}
                        </div>
                        {renderBullets(job.desc)}
                     </div>
                   </div>
                ))}
             </div>
          </section>
        )}

        {/* 5. Experience - Internships separated */}
        {data.internships && data.internships.length > 0 && (
          <section>
             <h2 className="text-[14px] sm:text-[15px] font-bold uppercase mb-[2px]">Internships & Co-ops</h2>
             <hr className="border-t border-black mb-2" />
             <div className="space-y-4">
                {data.internships.map((intern, idx) => (
                   <div key={idx} className="flex justify-between items-start text-[13px]">
                     <div className="w-[120px] shrink-0 font-medium leading-snug mt-0.5 whitespace-nowrap">
                        {intern.dates || "Date"}
                     </div>
                     <div className="flex-1">
                        <div className="font-bold leading-snug">
                          <span className="uppercase">{intern.role}</span>
                          {intern.org && <span>, {intern.org}</span>}
                        </div>
                        {renderBullets(intern.desc)}
                     </div>
                   </div>
                ))}
             </div>
          </section>
        )}

        {/* 6. Skills */}
        {data.skills && data.skills.length > 0 && (
          <section>
             <h2 className="text-[14px] sm:text-[15px] font-bold uppercase mb-[2px]">Skills</h2>
             <hr className="border-t border-black mb-1.5" />
             <div className="text-[13px] leading-snug">
               <span className="font-bold">Technical: </span>
               {data.skills.join(', ')}
             </div>
          </section>
        )}

        {/* 7. Bottom Lists: Hobbies / Languages / Footer attributes */}
        <section className="pt-2">
           <h2 className="text-[14px] sm:text-[15px] font-bold uppercase mb-[2px]">Additional Information</h2>
           <hr className="border-t border-black mb-1.5" />
           <div className="grid grid-cols-2 gap-4 text-[13px] leading-snug">
             <div>
               <span className="font-bold">Languages:</span> English (Native)
             </div>
             <div>
               <span className="font-bold">Hobbies:</span> Reading, Technology, Sports
             </div>
             <div>
               <span className="font-bold">Date of Birth:</span> Provided on request
             </div>
             <div>
               <span className="font-bold">Nationality:</span> Provided on request
             </div>
           </div>
        </section>

      </div>
    </div>
  );
}
