"use client";

import React from 'react';

interface Experience {
  company: string;
  role: string;
  bullets: string[];
}

interface ResumeData {
  name: string;
  email: string;
  skills: string[];
  experience: Experience[];
}

export default function ResumePreview({ data }: { data: ResumeData }) {
  if (!data) return null;

  return (
    <div className="bg-white text-zinc-900 p-12 shadow-2xl rounded-sm max-w-4xl mx-auto font-serif min-h-[1100px] border border-zinc-100 flex flex-col">
      {/* Header */}
      <header className="text-center mb-10 border-b-2 border-zinc-900 pb-8">
        <h1 className="text-4xl font-extrabold uppercase tracking-tight mb-2">{data.name || "Candidate Name"}</h1>
        <div className="flex justify-center items-center gap-4 text-xs font-bold uppercase tracking-widest text-zinc-500">
          <span>{data.email}</span>
          <span className="w-1.5 h-1.5 rounded-full bg-zinc-300"></span>
          <span>Professional Resume</span>
        </div>
      </header>

      <div className="flex-1 space-y-10">
        {/* Skills */}
        <section>
          <h2 className="text-sm font-black uppercase tracking-[0.3em] text-zinc-400 mb-4 border-b border-zinc-100 pb-2">Technical Proficiencies</h2>
          <div className="flex flex-wrap gap-2">
            {data.skills?.map((skill, i) => (
              <span key={i} className="bg-zinc-50 px-3 py-1 text-xs font-bold text-zinc-700 rounded border border-zinc-100">
                {skill}
              </span>
            ))}
          </div>
        </section>

        {/* Experience */}
        <section>
          <h2 className="text-sm font-black uppercase tracking-[0.3em] text-zinc-400 mb-6 border-b border-zinc-100 pb-2">Professional Experience</h2>
          <div className="space-y-8">
            {data.experience?.map((exp, i) => (
              <div key={i} className="group">
                <div className="flex justify-between items-baseline mb-2">
                  <h3 className="text-lg font-bold text-zinc-900">{exp.role}</h3>
                  <span className="text-[10px] font-black uppercase tracking-widest text-zinc-400">{exp.company}</span>
                </div>
                <ul className="list-disc list-outside ml-4 space-y-2">
                  {exp.bullets?.map((bullet, j) => (
                    <li key={j} className="text-sm text-zinc-600 leading-relaxed pl-2">
                      {bullet}
                    </li>
                  ))}
                </ul>
              </div>
            ))}
          </div>
        </section>
      </div>

      {/* Footer / Watermark */}
      <footer className="mt-20 pt-8 border-t border-zinc-100 text-[10px] font-bold text-zinc-300 uppercase tracking-[0.4em] flex justify-between items-center">
        <span>Generated by LandAJob Agent</span>
        <span>2026</span>
      </footer>
    </div>
  );
}
